// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface StoryblokResponse {
    articles: Articles;
}

export interface Articles {
    data:    Data;
    headers: { [key: string]: string };
}

export interface Data {
    stories: Story[];
    cv:      number;
    rels:    any[];
    links:   any[];
}

export interface Story {
    name:               string;
    created_at:         string;
    published_at:       string;
    id:                 number;
    uuid:               string;
    content:            StoryContent;
    slug:               string;
    full_slug:          string;
    sort_by_date:       null;
    position:           number;
    tag_list:           any[];
    is_startpage:       boolean;
    parent_id:          number;
    meta_data:          null;
    group_id:           string;
    first_published_at: string;
    release_id:         null;
    lang:               string;
    path:               null;
    alternates:         any[];
    default_full_slug:  null;
    translated_slugs:   null;
}

export interface StoryContent {
    _uid:       string;
    tags:       string[];
    image:      string;
    title:      string;
    author:     string;
    teaser:     string;
    content:    PurpleContent;
    component:  string;
    categories: string[];
    _editable:  string;
}

export interface PurpleContent {
    type:    string;
    content: FluffyContent[];
}

export interface FluffyContent {
    type:     FluffyType;
    content?: TentacledContent[];
}

export interface TentacledContent {
    text?:  string;
    type:   PurpleType;
    attrs?: Attrs;
}

export interface Attrs {
    alt:       string;
    src:       string;
    title:     string;
    copyright: string;
}

export enum PurpleType {
    HardBreak = "hard_break",
    Image = "image",
    Text = "text",
}

export enum FluffyType {
    Paragraph = "paragraph",
}
